// <auto-generated />
using System;
using Arauco.ProjectHub.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arauco.ProjectHub.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(IniciativasDbContext))]
    [Migration("20260701100050_EsquemaInicialCu002")]
    partial class EsquemaInicialCu002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Iniciativa", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("identificador");

                    b.Property<string>("BeneficioEsperado")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("beneficio_esperado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("justificacion");

                    b.Property<Guid>("NegocioIdentificador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("negocio_identificador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("objetivo");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Identificador");

                    b.HasIndex("NegocioIdentificador")
                        .HasDatabaseName("IX_iniciativa_negocio_identificador");

                    b.ToTable("iniciativa", null, t =>
                        {
                            t.HasCheckConstraint("CK_iniciativa_nombre_no_vacio", "LEN(LTRIM(RTRIM([nombre]))) > 0");

                            t.HasCheckConstraint("CK_iniciativa_objetivo_no_vacio", "LEN(LTRIM(RTRIM([objetivo]))) > 0");
                        });
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Negocio", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("identificador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Identificador");

                    b.ToTable("negocio", null, t =>
                        {
                            t.HasCheckConstraint("CK_negocio_nombre_no_vacio", "LEN(LTRIM(RTRIM([nombre]))) > 0");
                        });
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Participante", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("identificador");

                    b.Property<string>("IdentificacionPersonaOEquipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("identificacion_persona_o_equipo");

                    b.Property<Guid?>("IdentificadorTenant")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("identificador_tenant");

                    b.Property<Guid>("IniciativaIdentificador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("iniciativa_identificador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("ObjectIdentifier")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("object_identifier");

                    b.Property<string>("RolParticipacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rol_participacion");

                    b.HasKey("Identificador");

                    b.HasIndex("IniciativaIdentificador")
                        .HasDatabaseName("IX_participante_iniciativa_identificador");

                    b.HasIndex("IniciativaIdentificador", "IdentificadorTenant", "ObjectIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_participante_identidad_corporativa")
                        .HasFilter("[identificador_tenant] IS NOT NULL AND [object_identifier] IS NOT NULL");

                    b.ToTable("participante", null, t =>
                        {
                            t.HasCheckConstraint("CK_participante_identidad_corporativa_conjunta", "([identificador_tenant] IS NULL AND [object_identifier] IS NULL) OR ([identificador_tenant] IS NOT NULL AND [object_identifier] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Iniciativa", b =>
                {
                    b.HasOne("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Negocio", "Negocio")
                        .WithMany("Iniciativas")
                        .HasForeignKey("NegocioIdentificador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Participante", b =>
                {
                    b.HasOne("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Iniciativa", "Iniciativa")
                        .WithMany("Participantes")
                        .HasForeignKey("IniciativaIdentificador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Iniciativa");
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Iniciativa", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Arauco.ProjectHub.Infrastructure.Persistencia.Modelo.Negocio", b =>
                {
                    b.Navigation("Iniciativas");
                });
#pragma warning restore 612, 618
        }
    }
}
